### ISSUE TITLE
notification is undefined

### ISSUE THREAD

**Issue by DiscoTim** [Nickersoft/push.js#65] opened 2016-08-11 12:36 UTC
i receive this error in FF on Win 10 when i click the notification that pops up on the demo site: https://nickersoft.github.io/push.js/

TypeError: notification is undefined
Push/closeNotification()push.min.js:97
Push/createCallback/wrapper.close()push.min.js:245
Push/createCallback/<()push.min.js:252
1push.min.js:97:1

which is line 97 in the non-minified script:

if (notification.close) {

**Comment by Nickersoft** [comment] 2016-08-11 14:35
Checking just now, I'm not getting this issue on FF 47 (on OSX El Capitan), but I have Windows 10 duel-booted on my Mac back at home, so I'll definitely investigate later today. I've marked it as high priority. Seems something might be fishy going on with how Push is handling notification IDs.

**Comment by DiscoTim** [comment] 2016-08-11 18:38
i noticed this error in my own app, so i went to check on your demo, and same error. i'm using FF 48 on win 10. i am going to double check with a longer timeout, but it seems the time of the error corresponds to that. ie.. click the notifications and it closes, then the error appears when the timeout would have expired.

**Comment by DiscoTim** [comment] 2016-08-11 18:55
the timing of the error corresponds to the timeout. the error only occurs if the notification is clicked and closed, and for example.. if there is a 15 second timeout the error will appear after 15 seconds.

also, same error in chrome on win 10.

**Comment by Nickersoft** [comment] 2016-08-11 18:57
Yeah, I agree. When the timeout expires, it calls `notification.close()`, which is where the issue is occurring. `notification` is being pulled from the global list of notifications (the same one that `Push.count()` uses), which must not be functioning properly.

**Comment by Nickersoft** [comment] 2016-08-14 02:14
So I finally got a chance to test this on Firefox 48 on Windows 10 and MacOS Sierra, and I able to confirm the issue. I think you are correct, it is most likely being destroyed twice. I'll see what I can do to fix it.

**Comment by Nickersoft** [comment] 2016-08-14 02:26
Commit 26387abffd7da39736f6c3a24440fd70178c4d9e resolves this issue using a fix similar to the one mentioned in #66. Closing this ticket.

**Closed by Nickersoft** 2016-08-14 02:26 UTC
Labels: bug, Firefox, P1, Windows

**Comment by DiscoTim** [comment] 2016-08-15 16:05
thats excellent! thank you very much. will you be pushing this to cdnjs? the current version there is 0.0.10

**Comment by Nickersoft** [comment] 2016-08-16 02:04
Yup! Very soon :) Just wanted to wait a bit to make sure no bugs were being reported with the new code changes.
